{
    "version": 2,
    "updates": [
        {
            "package-ecosystem": "composer",
            "directory": "/",
            "allow": [
                {
                    "dependency-type": "all"
                }
            ],
            "schedule": {
                "interval": "weekly"
            },
            "versioning-strategy": "increase"
        },
        {
            "package-ecosystem": "github-actions",
            "directory": "/",
            "schedule": {
                "interval": "weekly"
            }
        }
    ]
}
